= Asciidoctor containor with PlantUML and japanese font.

Docker image of asciidoctor that include PlantUML. In order to use japanese for plantuml code, this image is having japanese font(IPA).

== Usage

=== Basic

Following is command for convert to html.

[source,sh]
--
$ docker run \
    -v ${your-asciidoc-file-directory}:/doc/ \
    --rm \
    aozk/docker-j-asciidoctor \
    ${asciidoctor-options-if-necessary} \
    ${asciidoc-file-name}
--

Also, you can convert to pdf using asciidoctor-pdf.

[source,sh]
--
$ docker run \
    -v ${your-asciidoc-file-directory}:/doc/ \
    --rm \
    -r asciidoctor-pdf \
    -r asciidoctor-pdf-cjk \
    -b pdf \
    aozk/docker-j-asciidoctor \
    ${asciidoctor-options-if-necessary} \
    ${asciidoc-file-name}
--

Follows is example that convert to html from this readme.adoc.

[source,sh]
--
$ docker run -v ${PWD}:/doc/ --rm aozk/docker-j-asciidoctor README.adoc
--

If you want look help of asciidoctor...

[source,sh]
--
$ docker run -v ${PWD}:/doc/ --rm aozk/docker-j-asciidoctor --help
--

=== Use script

I think that most people do not want to enter commands that are too long. So I made a simple startup script.

.Convert to HTML
[source,sh]
--
$ adoc ${asciidoctor-options-if-necessary} ${asciidoctor-file-name}
--

.Convert to PDF
[source,sh]
--
$ apdf ${asciidoctor-options-if-necessary} ${asciidoctor-file-name}
--

=== Work in containor

If you want do something oparation on containor, make overwrite entrypoint to '' and set cmd to '/bin/sh' as docker run argument.

[source,sh]
--
$ docker run -v ${PWD}:/doc/ --rm --entrypoint="" aozk/docker-j-asciidoctor /bin/sh
--

== Dependency

Docker version 18.06.01-ce or higher(may be).

== Setup

Pull image from dockerhub.

[source,sh]
--
$ docker pull aozk/docker-j-asciidoctor
--

Or execute `docker build` on root directory of this project.

[source,sh]
--
$ docker build -t .
--

== License

The MIT License.

== Reference

- link:https://asciidoctor.org/[]
- link:https://asciidoctor.org/docs/asciidoctor-diagram/[]
- link:http://plantuml.com/[]
